// Tabela de tradução de nomes de países EN → PT
// A WeatherAPI /search.json devolve sempre o nome do país em inglês.
// Este mapa é usado para traduzir o nome do país nas sugestões quando a língua é PT.
export const COUNTRY_PT: Record<string, string> = {
  'Afghanistan': 'Afeganistão',
  'Albania': 'Albânia',
  'Algeria': 'Argélia',
  'Angola': 'Angola',
  'Argentina': 'Argentina',
  'Armenia': 'Arménia',
  'Australia': 'Austrália',
  'Austria': 'Áustria',
  'Azerbaijan': 'Azerbaijão',
  'Bahrain': 'Barém',
  'Bangladesh': 'Bangladexe',
  'Belarus': 'Bielorrússia',
  'Belgium': 'Bélgica',
  'Bolivia': 'Bolívia',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  'Botswana': 'Botsuana',
  'Brazil': 'Brasil',
  'Bulgaria': 'Bulgária',
  'Cambodia': 'Camboja',
  'Cameroon': 'Camarões',
  'Canada': 'Canadá',
  'Chile': 'Chile',
  'China': 'China',
  'Colombia': 'Colômbia',
  'Congo': 'Congo',
  'Costa Rica': 'Costa Rica',
  'Croatia': 'Croácia',
  'Cuba': 'Cuba',
  'Cyprus': 'Chipre',
  'Czech Republic': 'República Checa',
  'Czechia': 'República Checa',
  'Denmark': 'Dinamarca',
  'Dominican Republic': 'República Dominicana',
  'Ecuador': 'Equador',
  'Egypt': 'Egito',
  'El Salvador': 'Salvador',
  'Estonia': 'Estónia',
  'Ethiopia': 'Etiópia',
  'Finland': 'Finlândia',
  'France': 'França',
  'Georgia': 'Geórgia',
  'Germany': 'Alemanha',
  'Ghana': 'Gana',
  'Greece': 'Grécia',
  'Guatemala': 'Guatemala',
  'Honduras': 'Honduras',
  'Hungary': 'Hungria',
  'Iceland': 'Islândia',
  'India': 'Índia',
  'Indonesia': 'Indonésia',
  'Iran': 'Irão',
  'Iraq': 'Iraque',
  'Ireland': 'Irlanda',
  'Israel': 'Israel',
  'Italy': 'Itália',
  'Jamaica': 'Jamaica',
  'Japan': 'Japão',
  'Jordan': 'Jordânia',
  'Kazakhstan': 'Cazaquistão',
  'Kenya': 'Quénia',
  'Kuwait': 'Kuwait',
  'Latvia': 'Letónia',
  'Lebanon': 'Líbano',
  'Libya': 'Líbia',
  'Lithuania': 'Lituânia',
  'Luxembourg': 'Luxemburgo',
  'Malaysia': 'Malásia',
  'Malta': 'Malta',
  'Mexico': 'México',
  'Moldova': 'Moldávia',
  'Mongolia': 'Mongólia',
  'Montenegro': 'Montenegro',
  'Morocco': 'Marrocos',
  'Mozambique': 'Moçambique',
  'Myanmar': 'Mianmar',
  'Namibia': 'Namíbia',
  'Nepal': 'Nepal',
  'Netherlands': 'Países Baixos',
  'New Zealand': 'Nova Zelândia',
  'Nicaragua': 'Nicarágua',
  'Nigeria': 'Nigéria',
  'North Korea': 'Coreia do Norte',
  'North Macedonia': 'Macedónia do Norte',
  'Norway': 'Noruega',
  'Oman': 'Omã',
  'Pakistan': 'Paquistão',
  'Palestine': 'Palestina',
  'Panama': 'Panamá',
  'Paraguay': 'Paraguai',
  'Peru': 'Peru',
  'Philippines': 'Filipinas',
  'Poland': 'Polónia',
  'Portugal': 'Portugal',
  'Qatar': 'Catar',
  'Romania': 'Roménia',
  'Russia': 'Rússia',
  'Saudi Arabia': 'Arábia Saudita',
  'Senegal': 'Senegal',
  'Serbia': 'Sérvia',
  'Singapore': 'Singapura',
  'Slovakia': 'Eslováquia',
  'Slovenia': 'Eslovénia',
  'Somalia': 'Somália',
  'South Africa': 'África do Sul',
  'South Korea': 'Coreia do Sul',
  'Spain': 'Espanha',
  'Sri Lanka': 'Sri Lanca',
  'Sudan': 'Sudão',
  'Sweden': 'Suécia',
  'Switzerland': 'Suíça',
  'Syria': 'Síria',
  'Taiwan': 'Taiwan',
  'Tanzania': 'Tanzânia',
  'Thailand': 'Tailândia',
  'Tunisia': 'Tunísia',
  'Turkey': 'Turquia',
  'Turkmenistan': 'Turquemenistão',
  'Uganda': 'Uganda',
  'Ukraine': 'Ucrânia',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'United Kingdom': 'Reino Unido',
  'United States of America': 'Estados Unidos',
  'United States': 'Estados Unidos',
  'Uruguay': 'Uruguai',
  'Uzbekistan': 'Uzbequistão',
  'Venezuela': 'Venezuela',
  'Vietnam': 'Vietname',
  'Yemen': 'Iémen',
  'Zambia': 'Zâmbia',
  'Zimbabwe': 'Zimbábue',
};

// Traduz o nome do país para o idioma ativo
// Mapa ISO-2 → nome PT (para registos antigos no histórico que guardaram código ISO)
const ISO2_PT: Record<string, string> = {
  'AF':'Afeganistão','AL':'Albânia','DZ':'Argélia','AO':'Angola','AR':'Argentina',
  'AM':'Arménia','AU':'Austrália','AT':'Áustria','AZ':'Azerbaijão','BH':'Barém',
  'BD':'Bangladexe','BY':'Bielorrússia','BE':'Bélgica','BO':'Bolívia','BA':'Bósnia e Herzegovina',
  'BW':'Botsuana','BR':'Brasil','BG':'Bulgária','KH':'Camboja','CM':'Camarões',
  'CA':'Canadá','CL':'Chile','CN':'China','CO':'Colômbia','CG':'Congo','CR':'Costa Rica',
  'HR':'Croácia','CU':'Cuba','CY':'Chipre','CZ':'República Checa','DK':'Dinamarca',
  'DO':'República Dominicana','EC':'Equador','EG':'Egito','SV':'Salvador','EE':'Estónia',
  'ET':'Etiópia','FI':'Finlândia','FR':'França','GE':'Geórgia','DE':'Alemanha',
  'GH':'Gana','GR':'Grécia','GT':'Guatemala','HN':'Honduras','HU':'Hungria',
  'IS':'Islândia','IN':'Índia','ID':'Indonésia','IR':'Irão','IQ':'Iraque',
  'IE':'Irlanda','IL':'Israel','IT':'Itália','JM':'Jamaica','JP':'Japão','JO':'Jordânia',
  'KZ':'Cazaquistão','KE':'Quénia','KW':'Kuwait','KG':'Quirguistão','LV':'Letónia',
  'LB':'Líbano','LY':'Líbia','LT':'Lituânia','MY':'Malásia','MX':'México',
  'MD':'Moldávia','MN':'Mongólia','MA':'Marrocos','MZ':'Moçambique','MM':'Mianmar',
  'NP':'Nepal','NL':'Países Baixos','NZ':'Nova Zelândia','NI':'Nicarágua','NG':'Nigéria',
  'NO':'Noruega','OM':'Omã','PK':'Paquistão','PA':'Panamá','PY':'Paraguai',
  'PE':'Peru','PH':'Filipinas','PL':'Polónia','PT':'Portugal','QA':'Qatar',
  'RO':'Roménia','RU':'Rússia','SA':'Arábia Saudita','SN':'Senegal','RS':'Sérvia',
  'SG':'Singapura','SK':'Eslováquia','SI':'Eslovénia','SO':'Somália','ZA':'África do Sul',
  'KR':'Coreia do Sul','ES':'Espanha','LK':'Sri Lanca','SD':'Sudão','SE':'Suécia',
  'CH':'Suíça','SY':'Síria','TW':'Taiwan','TJ':'Tajiquistão','TZ':'Tanzânia',
  'TH':'Tailândia','TN':'Tunísia','TR':'Turquia','TM':'Turquemenistão','UG':'Uganda',
  'UA':'Ucrânia','AE':'Emirados Árabes Unidos','GB':'Reino Unido','US':'Estados Unidos',
  'UY':'Uruguai','UZ':'Uzbequistão','VE':'Venezuela','VN':'Vietname','YE':'Iémen',
  'ZM':'Zâmbia','ZW':'Zimbábue','MK':'Macedónia do Norte','LU':'Luxemburgo',
  'MT':'Malta','ME':'Montenegro','MU':'Maurícia','NA':'Namíbia','PR':'Porto Rico',
};

// Mapa ISO-2 → nome EN (para converter código em nome antes de traduzir)
const ISO2_EN: Record<string, string> = {
  'AF':'Afghanistan','AL':'Albania','DZ':'Algeria','AO':'Angola','AR':'Argentina',
  'AM':'Armenia','AU':'Australia','AT':'Austria','AZ':'Azerbaijan','BH':'Bahrain',
  'BD':'Bangladesh','BY':'Belarus','BE':'Belgium','BO':'Bolivia','BA':'Bosnia and Herzegovina',
  'BW':'Botswana','BR':'Brazil','BG':'Bulgaria','KH':'Cambodia','CM':'Cameroon',
  'CA':'Canada','CL':'Chile','CN':'China','CO':'Colombia','CG':'Congo','CR':'Costa Rica',
  'HR':'Croatia','CU':'Cuba','CY':'Cyprus','CZ':'Czech Republic','DK':'Denmark',
  'DO':'Dominican Republic','EC':'Ecuador','EG':'Egypt','SV':'El Salvador','EE':'Estonia',
  'ET':'Ethiopia','FI':'Finland','FR':'France','GE':'Georgia','DE':'Germany',
  'GH':'Ghana','GR':'Greece','GT':'Guatemala','HN':'Honduras','HU':'Hungary',
  'IS':'Iceland','IN':'India','ID':'Indonesia','IR':'Iran','IQ':'Iraq',
  'IE':'Ireland','IL':'Israel','IT':'Italy','JM':'Jamaica','JP':'Japan','JO':'Jordan',
  'KZ':'Kazakhstan','KE':'Kenya','KW':'Kuwait','KG':'Kyrgyzstan','LV':'Latvia',
  'LB':'Lebanon','LY':'Libya','LT':'Lithuania','MY':'Malaysia','MX':'Mexico',
  'MD':'Moldova','MN':'Mongolia','MA':'Morocco','MZ':'Mozambique','MM':'Myanmar',
  'NP':'Nepal','NL':'Netherlands','NZ':'New Zealand','NI':'Nicaragua','NG':'Nigeria',
  'NO':'Norway','OM':'Oman','PK':'Pakistan','PA':'Panama','PY':'Paraguay',
  'PE':'Peru','PH':'Philippines','PL':'Poland','PT':'Portugal','QA':'Qatar',
  'RO':'Romania','RU':'Russia','SA':'Saudi Arabia','SN':'Senegal','RS':'Serbia',
  'SG':'Singapore','SK':'Slovakia','SI':'Slovenia','SO':'Somalia','ZA':'South Africa',
  'KR':'South Korea','ES':'Spain','LK':'Sri Lanka','SD':'Sudan','SE':'Sweden',
  'CH':'Switzerland','SY':'Syria','TW':'Taiwan','TJ':'Tajikistan','TZ':'Tanzania',
  'TH':'Thailand','TN':'Tunisia','TR':'Turkey','TM':'Turkmenistan','UG':'Uganda',
  'UA':'Ukraine','AE':'United Arab Emirates','GB':'United Kingdom','US':'United States',
  'UY':'Uruguay','UZ':'Uzbekistan','VE':'Venezuela','VN':'Vietnam','YE':'Yemen',
  'ZM':'Zambia','ZW':'Zimbabwe',
};

/**
 * Traduz o nome do país para o idioma activo.
 * Aceita:
 *   - nome completo em inglês  ("Portugal", "France")
 *   - código ISO-2             ("PT", "FR")  — registos antigos no histórico
 *   - nome já em português     (devolvido sem alteração quando lang=pt)
 */
export function translateCountry(name: string, lang: string): string {
  if (!name) return '';

  // Código ISO-2 (exactamente 2 letras maiúsculas)
  if (/^[A-Z]{2}$/.test(name)) {
    if (lang === 'pt') return ISO2_PT[name] ?? ISO2_EN[name] ?? name;
    return ISO2_EN[name] ?? name;
  }

  // Nome completo
  if (lang !== 'pt') return name;
  return COUNTRY_PT[name] ?? name;
}
